# Generated by Django 4.2.4 on 2023-08-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('age', models.IntegerField(blank=True, max_length=3, null=True)),
                ('email', models.EmailField(max_length=70)),
            ],
        ),
    ]
